# Generated by Django 5.1.2 on 2024-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseifyapp', '0003_alter_configuration_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
