# Generated by Django 5.1.2 on 2024-10-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseifyapp', '0004_alter_billingaddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdat',
            new_name='createdate',
        ),
    ]
