# Generated by Django 5.1.2 on 2024-10-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseifyapp', '0005_rename_createdat_order_createdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdate',
            new_name='createddate',
        ),
    ]
